Sea creatures
jballands/what-can-i-catch-now pull request #2
Opened 2020-07-10 16:15 UTC by MaxxWyndham

Added data and UI for the sea creatures introduced in 1.3.0
Also fixed walking stick times.

2020-07-12 21:24 UTC, MaxxWyndham commented
Available for preview here: https://what-can-i-catch-now.errolerrolson.vercel.app/

2020-07-13 17:29 UTC, FeXd commented
Looks awesome, great addition!

2020-07-28 16:00 UTC, jballands requested changes
Nice! Thanks for the data and the images, that stuff is really hard to get... I had to write a scrapper for the ACNH wiki.

I just left one comment regarding desktop displays. It doesn't look great side by side: 
<img width="1392" alt="Screen Shot 2020-07-28 at 10 56 35 AM" src="https://user-images.githubusercontent.com/2644971/88690671-82cd9c80-d0c1-11ea-8a42-6aee92f3ca41.png">

I think I'm gonna implement tabs once this goes in :)

2020-07-28 16:00 UTC, jballands commented on src/Critters/index.tsx
> +			gridTemplateColumns={['100%', '100%', '1fr 1fr 1fr']}
Let's keep this `1fr 1fr` for now so that it doesn't display weird on desktop displays. I think I have an idea that'll make navigating between creatures easier.

2020-07-28 23:41 UTC, MaxxWyndham commented
I've made the 1fr amend as requested above.  I hadn't noticed that display issue as it only seems to occur on desktop at 1366px wide and below.  Looks fine for me at 1920!

![image](https://user-images.githubusercontent.com/4244568/88740070-19d33c80-d134-11ea-9dd1-15597700caae.png)

2020-07-29 00:53 UTC, merged

2020-07-29 00:54 UTC, jballands commented
@MaxxWyndham No worries! Yeah I think the maximum amount of data is showing right now so I think a simple tab layout will help!

Thanks for the PR!